name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


env:
  ORG: jpbnetley
  REPO: ah-action-B
  WORKFLOW: ah-b-workflow.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: setup compisit env
          run: |
            echo "FULL_REPO=${{env.ORG}}/${{env.REPO}}" >> $GITHUB_ENV
        - name: trigger remote    
          run: |
            gh workflow run ${{ env.WORKFLOW }} -R ${{ env.FULL_REPO }}
            sleep 5
            gh run watch -R  ${{ env.FULL_REPO }} $(gh run list -R  ${{ env.FULL_REPO }} -w  ${{ env.WORKFLOW }} -L1 --json databaseId --jq .[0].databaseId)
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      
      # - uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.PAT_TOKEN }}
      #     script: |
      #       await github.rest.actions.createWorkflowDispatch({
      #         owner: 'jpbnetley',
      #         repo: 'ah-action-B',
      #         workflow_id: 'ah-b-workflow.yml',
      #         ref: 'main'
      #       })
